ALTER TABLE ongeki_user_gacha
    DROP FOREIGN KEY IF EXISTS FK_ONGEKI_USER_GACHA_ON_USER;
ALTER TABLE ongeki_user_gacha
    ADD CONSTRAINT FK_ONGEKI_USER_GACHA_ON_USER
        FOREIGN KEY (user_id) REFERENCES ongeki_user_data (id)
            ON DELETE CASCADE ON UPDATE CASCADE;
